# Generated by Django 3.1.3 on 2020-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='txt',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.CharField(max_length=50),
        ),
    ]
