# Generated by Django 3.1.3 on 2020-11-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201129_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
