# Generated by Django 3.1.3 on 2020-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20201129_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_obj', models.JSONField(null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
