# Generated by Django 3.1.3 on 2020-12-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20201202_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='list_obj',
            field=models.JSONField(null=True),
        ),
    ]
